name: Lint
on:
  push:
    branches: ["19.0", "19.0-*"]
  pull_request:
    branches: ["19.0"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.1
